### ISSUE TITLE
cuando se agregan componentes, no se agregan en la tabla "proveedores_componentes"

### ISSUE THREAD

**Issue by EmanuelSCH** [WalRuS10/SGRC#12]
cuando hacemos las operaciones con los componentes, no se actualiza esta tabla, solamente se actualiza el de la tabla componentes

**Comment by WalRuS10** [comment]
como seria la descripcion de la falla? los pasos a seguir para q se produzca?

**Comment by EmanuelSCH** [comment]
en realidad no es una falla o un bug, directamente es algo que no se programo, hay que hacer una alta en esa tabla cada vez que se agrega un componente

**Comment by WalRuS10** [comment]
yo creo de que si esxiste un componente, no necesariamente tiene que haber un proveedor. es decir uno puede crear el componente sin tener que preocuparse por los proveedores del mismo. si se desea necesariamente agregar proveedores para ese componente, al crear un componente se podria redirijir al controlador a la edicion del mismo para que en caso de ser extrictamente necesario, agregar el o los proveedores.
